type Geo {
  lat: Float!
  lng: Float!
}

type Address {
  street: String!
  suite: String!
  city: String!
  zipcode: String!
  geo: Geo!
}

type User {
  id: ID!
  name: String!
  username: String!
  email: String!
  address: Address!
  todos: [Todo!]!
}

type Todo {
  id: ID!
  title: String! @stream
  user: User @defer
}

extend type Query {
  todos(skip: Int, limit: Int): [Todo!]!
  todo(id: ID!): Todo! @deprecated
  users: [User!]!
}
